---
version: '3.8'
services:
  frontend:
    build:
      context: ./nexus-frontend
      dockerfile: Dockerfile
    ports:
      - '4200:80'
#
#  backend:
#    image: openjdk:17
#    working_dir: /app
#    volumes:
#      - .:/app
#    command: ["java", "-jar", "backend.jar"]
#    ports:
#      - "8080:8080"
