---
name: Frontend-CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    name: Build & Test (Unit, Integration, Smoke)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run Unit Tests
        env:
          CHROME_BIN: /usr/bin/google-chrome
        run: |
          sudo apt-get update && sudo apt-get install -y google-chrome-stable
          npm run test:unit

      - name: Run Integration Tests
        env:
          CHROME_BIN: /usr/bin/google-chrome
        run: |
          npm run test:integration

      - name: Build Angular app
        run: npm run build --if-present

#      - name: Run Smoke Tests
#        run: |
#          npm run test:smoke

#      - name: Install Google Chrome
#        run: |
#          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
#          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
#          sudo apt-get update
#          sudo apt-get install -y google-chrome-stable
#      - name: Run Karma tests
#        env:
#          CHROME_BIN: /usr/bin/google-chrome
#        run: npm run test -- --watch=false --browsers=ChromeHeadlessNoSandbox
#      - name: Install Playwright Browsers
#        run: npx playwright install --with-deps
#      - name: Run Angular app and Playwright tests
#        run: npx start-server-and-test "npm start"
#          http://localhost:4200 "npx playwright test"
